using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SnakeLadderProblem
{
   public class StartUC1
    {
        public static void FindStartUC1()
        {
            Console.WriteLine("Welcome in Snake and Ladder Problem");
            int start = 0;
            Console.WriteLine("The begining of Game is : "+start);
        }
    }
}
